services:
  app:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - ./Caddyfile:/etc/frankenphp/Caddyfile
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:16-alpine"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
