parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # This is the crucial new section that activates our decorator.
    # It tells Symfony: "When someone asks for the OpenApiFactory,
    # give them our JwtDecorator instead, and give our decorator
    # the original factory so it can do its job."
    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
        autoconfigure: false
